
[[dependencies]]
  name = "github.com/Sirupsen/logrus"
  revision = "5e5dc898656f695e2a086b8e12559febbfc01562"

[[dependencies]]
  name = "github.com/asaskevich/govalidator"
  revision = "fdf19785fd3558d619ef81212f5edf1d6c2a5911"

[[dependencies]]
  branch = "master"
  name = "github.com/aws/aws-sdk-go"

[[dependencies]]
  branch = "master"
  name = "github.com/crewjam/go-cloudformation"

[[dependencies]]
  branch = "master"
  name = "github.com/mweagle/cloudformationresources"

[[dependencies]]
  name = "github.com/spf13/cobra"
  revision = "ca57f0f5dba473a8a58765d16d7e811fb8027add"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/tools"
